# Generated by Django 2.2.8 on 2020-02-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=64)),
                ('FirstName', models.CharField(max_length=64)),
                ('LastName', models.CharField(max_length=64)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=64)),
                ('PhoneNumber', models.IntegerField()),
                ('Image', models.ImageField(upload_to='')),
                ('Requirement', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
            ],
        ),
    ]
