# Generated by Django 2.2.8 on 2020-02-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=64)),
                ('Requirements', models.CharField(max_length=1000)),
            ],
        ),
    ]
